// Auth types
export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const FETCH_USER = "FETCH_USER";
export const AFTER_AUTHERROR = "AFTER_AUTHERROR";
export const AUTH_MESSAGE = "AUTH_MESSAGE";
export const LOAD_AUTH = 'LOAD_AUTH';

// Projects Types
export const FETCH_SCHEDULES = "FETCH_PROJECTS";
export const UPDATE_SCHEDULE_DATE = "UPDATE_SCHEDULE_DATE";
export const UPDATE_SCHEDULE_CURRENTDAY = 'UPDATE_SCHEDULE_CURRENTDAY'

// Declarations Types
export const UPLOAD_DECLARATIONS = 'UPLOAD_DECLARATIONS';
export const SEND_DECLARATIONS = 'SEND_DECLARATIONS';
export const FINISH_DECLARATIONS = 'FINISH_DECLARATIONS';
export const RESET_DECLARATIONS = 'RESET_DECLARATIONS'

// Availability Types
export const FETCH_AVAILABILITY = "FETCH_AVAILABILITY";
export const UPDATE_AVAILABILITY_DATE = "UPDATE_AVAILABILITY_DATE";
export const UPDATE_AVAILABILITY_CURRENTDAY = 'UPDATE_AVAILABILITY_CURRENTDAY'
export const UPLOAD_AVAILABILITY = 'UPLOAD_AVAILABILITY';
export const SEND_AVAILABILITY = 'SEND_AVAILABILITY';
export const FINISH_AVAILABILITY = 'FINISH_AVAILABILITY';
export const ERROR_AVAILABILITY = 'ERROR_AVAILABILITY'
export const RESET_AVAILABILITY = 'RESET_AVAILABILITY'
export const UPDATE_AVAILABILITY_SCHEDULES = 'UPDATE_AVAILABILITY_SCHEDULES';

// Vriend aanmelden types
export const UPLOAD_VRIEND_AANMELDEN = 'UPLOAD_VRIEND_AANMELDEN';
export const SEND_VRIEND_AANMELDEN = 'SEND_VRIEND_AANMELDEN';
export const FINISH_VRIEND_AANMELDEN = 'FINISH_VRIEND_AANMELDEN';

// Salaris types
export const FETCH_SALARIS = 'FETCH_SALARIS';
export const UPDATE_SALARIS_DATE = "UPDATE_SALARIS_DATE";
export const UPDATE_SALARIS_CURRENTDAY = 'UPDATE_SALARIS_CURRENTDAY';
export const SEND_SALARIS = 'SEND_SALARIS';
export const FINISH_SALARIS = 'FINISH_SALARIS';
export const ERROR_SALARIS = 'ERROR_SALARIS';
export const UPDATE_SALARIS_DATE_MONTH = 'UPDATE_SALARIS_DATE_MONTH'


// score types
export const FETCH_SCORE = "FETCH_SCORE";
