<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertCountries extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        \Illuminate\Support\Facades\DB::insert("INSERT INTO countries (country) VALUES
    ('Onbekend'),
    ('Canada'),
    ('Frankrijk'),
    ('Zwitserland'),
    ('Rhodesië'),
    ('Malawi'),
    ('Cuba'),
    ('Suriname'),
    ('Tunesië'),
    ('Oostenrijk'),
    ('België'),
    ('Botswana'),
    ('Iran'),
    ('Nieuw-Zeeland'),
    ('Zuid-Afrika'),
    ('Denemarken'),
    ('Noord-Jemen'),
    ('Hongarije'),
    ('Saoedi-Arabië'),
    ('Liberia'),
    ('Ethiopië'),
    ('Chili'),
    ('Marokko'),
    ('Togo'),
    ('Ghana'),
    ('Laos'),
    ('Angola'),
    ('Filipijnen'),
    ('Zambia'),
    ('Mali'),
    ('Ivoorkust'),
    ('Burma'),
    ('Monaco'),
    ('Colombia'),
    ('Albanië'),
    ('Kameroen'),
    ('Zuid-Vietnam'),
    ('Singapore'),
    ('Paraguay'),
    ('Zweden'),
    ('Cyprus'),
    ('Australisch Nieuw-Guinea'),
    ('Brunei'),
    ('Irak'),
    ('Mauritius'),
    ('Vaticaanstad'),
    ('Kashmir'),
    ('Myanmar'),
    ('Jemen'),
    ('Slovenië'),
    ('Zaïre'),
    ('Kroatië'),
    ('Taiwan'),
    ('Rusland'),
    ('Armenië'),
    ('Ascension'),
    ('Azoren'),
    ('Bahrein'),
    ('Bhutan'),
    ('Britse Antillen'),
    ('Comoren'),
    ('Falklandeilanden'),
    ('Frans-Guyana'),
    ('Frans-Somaliland'),
    ('Gilbert- en Ellice-eilanden'),
    ('Groenland'),
    ('Guadeloupe'),
    ('Kaapverdische Eilanden'),
    ('Macau'),
    ('Martinique'),
    ('Mozambique'),
    ('Pitcairneilanden'),
    ('Guinee-Bissau'),
    ('Réunion'),
    ('Saint Pierre en Miquelon'),
    ('Seychellen en Amiranten'),
    ('Tonga'),
    ('Wallis en Futuna'),
    ('Zuidwest-Afrika'),
    ('Frans-Indië'),
    ('Johnston'),
    ('Kedah'),
    ('Kelantan'),
    ('Malakka'),
    ('Mayotte'),
    ('Negri Sembilan'),
    ('Pahang'),
    ('Perak'),
    ('Perlis'),
    ('Portugees-Indië'),
    ('Selangor'),
    ('Sikkim'),
    ('Saint Vincent en de Grenadines'),
    ('Spitsbergen'),
    ('Trengganu'),
    ('Aruba'),
    ('Burkina Faso'),
    ('Azerbeidzjan'),
    ('Belarus'),
    ('Kazachstan'),
    ('Macedonië'),
    ('Timor Leste'),
    ('Servië en Montenegro'),
    ('Servië'),
    ('Montenegro'),
    ('Kosovo'),
    ('Bonaire'),
    ('Curaçao'),
    ('Saba'),
    ('Sint Eustatius'),
    ('Sint Maarten'),
    ('Zuid-Soedan'),
    ('Gazastrook en Westelijke Jordaanoever'),
    ('Republiek Noord-Macedonië'),
    ('Moldavië'),
    ('Burundi'),
    ('Finland'),
    ('Griekenland'),
    ('Guatemala'),
    ('Nigeria'),
    ('Libië'),
    ('Ierland'),
    ('Brazilië'),
    ('Rwanda'),
    ('Venezuela'),
    ('IJsland'),
    ('Liechtenstein'),
    ('Somalië'),
    ('Verenigde Staten van Amerika'),
    ('Bolivia'),
    ('Australië'),
    ('Jamaica'),
    ('Luxemburg'),
    ('Tsjaad'),
    ('Mauritanië'),
    ('Kirgizië'),
    ('China'),
    ('Afghanistan'),
    ('Indonesië'),
    ('Guyana'),
    ('Noord-Vietnam'),
    ('Noorwegen'),
    ('San Marino'),
    ('Duitsland'),
    ('Nederland'),
    ('Cambodja'),
    ('Fiji'),
    ('Bahama''s'),
    ('Israël'),
    ('Nepal'),
    ('Zuid-Korea'),
    ('Spanje'),
    ('Oekraïne'),
    ('Groot-Brittannië'),
    ('Niger'),
    ('Haïti'),
    ('Jordanië'),
    ('Turkije'),
    ('Trinidad en Tobago'),
    ('Joegoslavië'),
    ('Opper-Volta'),
    ('Algerije'),
    ('Gabon'),
    ('Noord-Korea'),
    ('Oezbekistan'),
    ('Sierra Leone'),
    ('Brits-Honduras'),
    ('Canarische Eilanden'),
    ('Frans-Polynesië'),
    ('Gibraltar'),
    ('Portugees-Timor'),
    ('Tadzjikistan'),
    ('Britse Salomonseilanden'),
    ('São Tomé en Principe'),
    ('Sint-Helena'),
    ('Tristan Da Cunha'),
    ('West-Samoa'),
    ('Turkmenistan'),
    ('Georgië'),
    ('Bosnië-Herzegovina'),
    ('Tsjechië'),
    ('Slowakije'),
    ('Federale Republiek Joegoslavië'),
    ('Democratische Republiek Congo'),
    ('Uganda'),
    ('Kenya'),
    ('Malta'),
    ('Barbados'),
    ('Andorra'),
    ('Mexico'),
    ('Costa Rica'),
    ('Gambia'),
    ('Syrië'),
    ('Nederlandse Antillen'),
    ('Zuid-Jemen'),
    ('Egypte'),
    ('Argentinië'),
    ('Lesotho'),
    ('Honduras'),
    ('Nicaragua'),
    ('Pakistan'),
    ('Senegal'),
    ('Dahomey'),
    ('Bulgarije'),
    ('Maleisië'),
    ('Dominicaanse Republiek'),
    ('Polen'),
    ('Rusland (oud)'),
    ('Britse Maagdeneilanden'),
    ('Tanzania'),
    ('El Salvador'),
    ('Sri Lanka'),
    ('Soedan'),
    ('Japan'),
    ('Hongkong'),
    ('Panama'),
    ('Uruguay'),
    ('Ecuador'),
    ('Guinee'),
    ('Maldiven'),
    ('Thailand'),
    ('Libanon'),
    ('Italië'),
    ('Koeweit'),
    ('India'),
    ('Roemenië'),
    ('Tsjecho-Slowakije'),
    ('Peru'),
    ('Portugal'),
    ('Oman'),
    ('Mongolië'),
    ('Samoa'),
    ('Verenigde Arabische Emiraten'),
    ('Tibet'),
    ('Nauru'),
    ('Nederlands Nieuw-Guinea'),
    ('Tanganyika'),
    ('Palestina'),
    ('Brits West-Indië'),
    ('Portugees-Afrika'),
    ('Letland'),
    ('Estland'),
    ('Litouwen'),
    ('Brits-Afrika'),
    ('Belgisch-Congo'),
    ('Brits-Indië'),
    ('Noord-Rhodesië'),
    ('Zuid-Rhodesië'),
    ('Saarland'),
    ('Frans Indochina'),
    ('Brits West-Borneo'),
    ('Goudkust'),
    ('Ras al-Khaimah'),
    ('Frans-Congo'),
    ('Siam'),
    ('Brits Oost-Afrika'),
    ('Brits Noord-Borneo'),
    ('Bangladesh'),
    ('Duitse Democratische Republiek'),
    ('Madeira-eilanden'),
    ('Amerikaanse Maagdeneilanden'),
    ('Australische Salomonseilanden'),
    ('Spaanse Sahara'),
    ('Caymaneilanden'),
    ('Caicoseilanden'),
    ('Turkseilanden'),
    ('Brits Antarctisch Territorium'),
    ('Brits Indische Oceaanterritorium'),
    ('Cookeilanden'),
    ('Tokelau'),
    ('Nieuw-Caledonië'),
    ('Hawaii-eilanden'),
    ('Guam'),
    ('Amerikaans-Samoa'),
    ('Midway'),
    ('Riukiu-eilanden'),
    ('Wake'),
    ('Pacific-eilanden'),
    ('Grenada'),
    ('Marianen'),
    ('Cabinda'),
    ('Canton en Enderbury'),
    ('Christmaseiland'),
    ('Cocoseilanden'),
    ('Faeröer'),
    ('Montserrat'),
    ('Norfolk'),
    ('Belize'),
    ('Tasmanië'),
    ('Turks- en Caicoseilanden'),
    ('Puerto Rico'),
    ('Papoea-Nieuw-Guinea'),
    ('Salomonseilanden'),
    ('Benin'),
    ('Vietnam'),
    ('Kaapverdië'),
    ('Seychellen'),
    ('Kiribati'),
    ('Tuvalu'),
    ('Saint Lucia'),
    ('Dominica'),
    ('Zimbabwe'),
    ('Dubai'),
    ('Nieuwe Hebriden'),
    ('Kanaaleilanden'),
    ('Man'),
    ('Anguilla'),
    ('Saint Kitts en Nevis'),
    ('Antigua'),
    ('Saint Vincent'),
    ('Gilberteilanden'),
    ('Panamakanaalzone'),
    ('Saint Kitts'),
    ('Nevis en Anguilla'),
    ('Belau'),
    ('Palau'),
    ('Antigua en Barbuda'),
    ('Newfoundland'),
    ('Nyasaland'),
    ('Eritrea'),
    ('Ifni'),
    ('Brits-Kameroen'),
    ('Keizer Wilhelmsland'),
    ('Congo'),
    ('Congo-Kinshasa'),
    ('Madagaskar'),
    ('Congo-Brazzaville'),
    ('Leewardeilanden'),
    ('Windwardeilanden'),
    ('Frans Territorium voor Afars en Issa''s'),
    ('Phoenixeilanden'),
    ('Portugees-Guinee'),
    ('Duits Zuidwest-Afrika'),
    ('Namibië'),
    ('Brits-Somaliland'),
    ('Italiaans-Somaliland'),
    ('Nederlands-Indië'),
    ('Brits-Guyana'),
    ('Swaziland'),
    ('Qatar'),
    ('Aden'),
    ('Zuid-Arabische Federatie'),
    ('Equatoriaal-Guinea'),
    ('Spaans-Guinee'),
    ('Verenigde Arabische Republiek'),
    ('Bermuda'),
    ('Sovjet-Unie'),
    ('Duits Oost-Afrika'),
    ('Zanzibar'),
    ('Ceylon'),
    ('Muscat en Oman'),
    ('Trucial Oman'),
    ('Indochina'),
    ('Marshalleilanden'),
    ('Sarawak'),
    ('Brits-Borneo'),
    ('Sabah'),
    ('Abu Dhabi'),
    ('Ajman'),
    ('Basutoland'),
    ('Bechuanaland'),
    ('Fujairah'),
    ('Frans-Kameroen'),
    ('Johore'),
    ('Korea'),
    ('Labuan'),
    ('Umm Al-Qaiwain'),
    ('Oostenrijk-Hongarije'),
    ('Portugees Oost-Afrika'),
    ('Portugees West-Afrika'),
    ('Sharjah'),
    ('Straits Settlements'),
    ('Abessinië'),
    ('Frans West-Afrika'),
    ('Frans Equatoriaal-Afrika'),
    ('Urundi'),
    ('Ruanda-Urundi'),
    ('Goa'),
    ('Dantzig'),
    ('Centraal-Afrikaanse Republiek'),
    ('Djibouti'),
    ('Transjordanië'),
    ('Bondsrepubliek Duitsland'),
    ('Vanuatu'),
    ('Niue'),
    ('Spaans Noord-Afrika'),
    ('Westelijke Sahara'),
    ('Micronesia'),
    ('Svalbardeilanden'),
    ('Internationaal gebied')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
