<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class InsertNationalties extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        \Illuminate\Support\Facades\DB::insert("INSERT INTO nationalities (nationality_code, name) VALUES (1, 'Nederlandse'),
       (2, 'Behandeld als Nederlander'),
       (27, 'Slowaakse'),
       (28, 'Tsjechische'),
       (29, 'Burger van Bosnië-Herzegovina'),
       (30, 'Georgische'),
       (31, 'Turkmeense'),
       (32, 'Tadzjiekse'),
       (33, 'Oezbeekse'),
       (34, 'Oekraïense'),
       (35, 'Kirgizische'),
       (36, 'Moldavische'),
       (37, 'Kazachse'),
       (38, 'Belarussische'),
       (39, 'Azerbeidzjaanse'),
       (40, 'Armeense'),
       (41, 'Russische'),
       (42, 'Sloveense'),
       (43, 'Kroatische'),
       (44, 'Letse'),
       (45, 'Estische'),
       (46, 'Litouwse'),
       (47, 'Marshalleilandse'),
       (48, 'Myanmarese'),
       (49, 'Namibische'),
       (50, 'Albanese'),
       (51, 'Andorrese'),
       (52, 'Belgische'),
       (53, 'Bulgaarse'),
       (54, 'Deense'),
       (55, 'Burger van de Bondsrepubliek Duitsland'),
       (56, 'Finse'),
       (57, 'Franse'),
       (58, 'Jemenitische'),
       (59, 'Griekse'),
       (60, 'Brits burger'),
       (61, 'Hongaarse'),
       (62, 'Ierse'),
       (63, 'IJslandse'),
       (64, 'Italiaanse'),
       (65, 'Joegoslavische'),
       (66, 'Liechtensteinse'),
       (67, 'Luxemburgse'),
       (68, 'Maltese'),
       (69, 'Monegaskische'),
       (70, 'Noorse'),
       (71, 'Oostenrijkse'),
       (72, 'Poolse'),
       (73, 'Portugese'),
       (74, 'Roemeense'),
       (75, 'Burger van de Sovjet-Unie'),
       (76, 'San Marinese'),
       (77, 'Spaanse'),
       (78, 'Tsjecho-Slowaakse'),
       (79, 'Vaticaanse'),
       (80, 'Zweedse'),
       (81, 'Zwitserse'),
       (82, 'Oost-Duitse'),
       (83, 'Brits onderdaan'),
       (84, 'Eritrese'),
       (85, 'Brits overzees burger'),
       (86, 'Macedonische'),
       (87, 'Kosovaarse'),
       (88, 'Burger van de Republiek Noord-Macedonië'),
       (100, 'Algerijnse'),
       (101, 'Angolese'),
       (104, 'Burundese'),
       (105, 'Botswaanse'),
       (106, 'Burkinese'),
       (108, 'Centraal-Afrikaanse'),
       (109, 'Comorese'),
       (110, 'Burger van Congo'),
       (111, 'Beninse'),
       (112, 'Egyptische'),
       (113, 'Equatoriaal-Guinese'),
       (114, 'Ethiopische'),
       (115, 'Djiboutiaanse'),
       (116, 'Gabonese'),
       (117, 'Gambiaanse'),
       (118, 'Ghanese'),
       (119, 'Guinese'),
       (120, 'Ivoriaanse'),
       (121, 'Kaapverdische'),
       (122, 'Kameroense'),
       (123, 'Kenyaanse'),
       (124, 'Zaïrese'),
       (125, 'Lesothaanse'),
       (126, 'Liberiaanse'),
       (127, 'Libische'),
       (128, 'Malagassische'),
       (129, 'Malawische'),
       (130, 'Malinese'),
       (131, 'Marokkaanse'),
       (132, 'Mauritaanse'),
       (133, 'Mauritiaanse'),
       (134, 'Mozambikaanse'),
       (135, 'Swazische'),
       (136, 'Nigerese'),
       (137, 'Nigeriaanse'),
       (138, 'Ugandese'),
       (139, 'Guinee-Bissause'),
       (140, 'Zuid-Afrikaanse'),
       (142, 'Zimbabwaanse'),
       (143, 'Rwandese'),
       (144, 'Burger van São Tomé en Principe'),
       (145, 'Senegalese'),
       (147, 'Sierra Leoonse'),
       (148, 'Soedanese'),
       (149, 'Somalische'),
       (151, 'Tanzaniaanse'),
       (152, 'Togolese'),
       (154, 'Tsjadische'),
       (155, 'Tunesische'),
       (156, 'Zambiaanse'),
       (157, 'Zuid-Soedanese'),
       (200, 'Bahamaanse'),
       (202, 'Belizaanse'),
       (204, 'Canadese'),
       (205, 'Costa Ricaanse'),
       (206, 'Cubaanse'),
       (207, 'Dominicaanse'),
       (208, 'Salvadoraanse'),
       (211, 'Guatemalaanse'),
       (212, 'Haïtiaanse'),
       (213, 'Hondurese'),
       (214, 'Jamaicaanse'),
       (216, 'Mexicaanse'),
       (218, 'Nicaraguaanse'),
       (219, 'Panamese'),
       (222, 'Burger van Trinidad en Tobago'),
       (223, 'Amerikaans burger'),
       (250, 'Argentijnse'),
       (251, 'Barbadaanse'),
       (252, 'Boliviaanse'),
       (253, 'Braziliaanse'),
       (254, 'Chileense'),
       (255, 'Colombiaanse'),
       (256, 'Ecuadoraanse'),
       (259, 'Guyaanse'),
       (261, 'Paraguayaanse'),
       (262, 'Peruaanse'),
       (263, 'Surinaamse'),
       (264, 'Uruguayaanse'),
       (265, 'Venezolaanse'),
       (267, 'Grenadaanse'),
       (268, 'Burger van Saint Kitts en Nevis'),
       (300, 'Afghaanse'),
       (301, 'Bahreinse'),
       (302, 'Bhutaanse'),
       (303, 'Burmaanse'),
       (304, 'Bruneise'),
       (305, 'Cambodjaanse'),
       (306, 'Sri Lankaanse'),
       (307, 'Chinese'),
       (308, 'Cyprische'),
       (309, 'Filipijnse'),
       (310, 'Taiwanese'),
       (312, 'Indiase'),
       (313, 'Indonesische'),
       (314, 'Iraakse'),
       (315, 'Iraanse'),
       (316, 'Israëlische'),
       (317, 'Japanse'),
       (318, 'Noord-Jemenitische'),
       (319, 'Jordaanse'),
       (320, 'Koeweitse'),
       (321, 'Laotiaanse'),
       (322, 'Libanese'),
       (324, 'Maldivische'),
       (325, 'Maleisische'),
       (326, 'Mongolische'),
       (327, 'Omaanse'),
       (328, 'Nepalese'),
       (329, 'Noord-Koreaanse'),
       (331, 'Pakistaanse'),
       (333, 'Qatarese'),
       (334, 'Saoedi-Arabische'),
       (335, 'Singaporese'),
       (336, 'Syrische'),
       (337, 'Thaise'),
       (338, 'Burger van de Verenigde Arabische Emiraten'),
       (339, 'Turkse'),
       (340, 'Zuid-Jemenitische'),
       (341, 'Zuid-Koreaanse'),
       (342, 'Vietnamese'),
       (345, 'Bengalese'),
       (400, 'Australische'),
       (401, 'Papoea-Nieuw-Guinese'),
       (402, 'Nieuw-Zeelandse'),
       (404, 'West-Samoaanse'),
       (405, 'Samoaanse'),
       (421, 'Burger van Antigua en Barbuda'),
       (424, 'Vanuatuaanse'),
       (425, 'Fijische'),
       (429, 'Burger van Britse afhankelijke gebieden'),
       (430, 'Tongaanse'),
       (431, 'Nauruaanse'),
       (432, 'Palause'),
       (437, 'Amerikaans onderdaan'),
       (442, 'Salomonseilandse'),
       (443, 'Micronesische'),
       (444, 'Seychelse'),
       (445, 'Kiribatische'),
       (446, 'Tuvaluaanse'),
       (447, 'Saint Luciaanse'),
       (448, 'Burger van Dominica'),
       (449, 'Burger van Saint Vincent en de Grenadines'),
       (450, 'British National (overseas)'),
       (451, 'Burger van Democratische Republiek Congo'),
       (452, 'Burger van Timor Leste'),
       (453, 'Burger van Servië en Montenegro'),
       (454, 'Servische'),
       (455, 'Montenegrijnse'),
       (499, 'Staatloos'),
       (500, 'Vastgesteld niet-Nederlander')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
