// Auth types
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_USER = 'FETCH_USER';
export const AFTER_AUTHERROR = "AFTER_AUTHERROR";
export const AUTH_MESSAGE = "AUTH_MESSAGE";
export const LOAD_AUTH = 'LOAD_AUTH';

// Projects Types
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const UPDATE_PROJECT_DATE = 'UPDATE_PROJECT_DATE';
export const ADD_SCHEDUELE = 'ADD_SCHEDUELE';
export const RESET_PROJECTS = 'RESET_PROJECTS';
export const RESET_PROJECT = 'RESET_PROJECT';
export const ERROR_PROJECTS = 'ERROR_PROJECTS';


// Employee Types
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const RESET_EMPLOYEES = 'RESET_EMPLOYEES'
export const RESET_EMPLOYEE = 'RESET_EMPLOYEE'
export const UPDATE_EMPLOYEE_SEARCH = 'UPDATE_EMPLOYEE_SEARCH';
export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES'
export const GET_EMPLOYEE_FORM = 'GET_EMPLOYEE_FORM';
export const TOGGLE_FORM_LOADING = 'TOGGLE_FORM_LOADING';

// Employee Create
export const ADD_EMPLOYEE_FORM = 'ADD_EMPLOYEE_FORM';
export const RESET_EMPLOYEE_FORM = 'RESET_EMPLOYEE_FORM';
export const FINISH_EMPLOYEE_FORM = 'FINISH_EMPLOYEE_FORM';
export const LOAD_EMPLOYEE_FORM = 'LOAD_EMPLOYEE_FORM';
export const ADD_EMPLOYEE_TAG = 'ADD_EMPLOYEE_TAG';
export const REMOVE_EMPLOYEE_TAG = 'REMOVE_EMPLOYEE_TAG';

// Table Types
export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const SET_TABLE_ERROR = 'SET_TABLE_ERROR';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const RESET_TABLE_DATA = 'RESET_TABLE_DATA'
export const UPDATE_TABLE_PAGE = 'UPDATE_TABLE_PAGE';
export const UPDATE_TABLE_SEARCH = 'UPDATE_TABLE_SEARCH';
export const SET_TABLE_BODY_LOADING = 'SET_TABLE_BODY_LOADING';
export const UPDATE_TABLE_SORT_BY = 'UPDATE_TABLE_SORT_BY';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';
export const FETCHING_TABLE_EXPORT = 'FETCHING_TABLE_EXPORT';
export const FINISHED_FETCHING_TABLE_EXPORT = 'FINISHED_FETCHING_TABLE_EXPORT';
export const UPDATE_TABLE_FILTER_EXTENSION = 'UPDATE_TABLE_FILTER_EXTENSION';
export const UPDATE_TABLE_FILTER = 'UPDATE_TABLE_FILTER';
export const RESET_TABLE = 'RESET_TABLE';
export const DELETE_TABLE_ROW_SUCCESS = 'DELETE_TABLE_ROW_SUCCESS';


// partner Types
export const FETCH_PARTNERS = 'FETCH_PARTNERS';
export const FETCH_PARTNER = 'FETCH_PARTNER';
export const SET_LOADING_PARTNERS = 'SET_LOADING_PARTNERS';
export const SET_FINISHED_PARTNERS = 'SET_FINISHED_PARTNERS';
export const RESET_PARTNER = 'RESET_PARTNER';
export const SET_PROJECT_FINISHED = 'SET_PROJECT_FINISHED';
export const FETCHING_PARTNERS = 'FETCHING_PARTNERS';
export const UNFETCHING_PARTNERS = 'UNFETCHING_PARTNERS';

//Subscription types
export const FETCH_SUBSCRIPTION = 'FETCH_SUBSCRIPTION';
export const SET_LOADING_SUBSCRIPTION = 'SET_LOADING_SUBSCRIPTION';
export const SET_FINISHED_SUBSCRIPTION = 'SET_FINISHED_SUBSCRIPTION';
export const RESET_SUBSCRIPTION = 'RESET_SUBSCRIPTION';
export const SET_FETCH_SUBSCRIPTION = 'SET_FETCH_SUBSCRIPTION';
export const SET_UNFETCH_SUBSCRIPTION = 'SET_UNFETCH_SUBSCRIPTION';
//Salaries types

export const FETCH_SALARY = 'FETCH_SALARY';
export const UPLOAD_SALARY = 'UPLOAD_SALARY';
export const FINISH_SALARY = 'FINISH_SALARY';
export const RESET_SALARY = 'RESET_SALARY ';
export const REMOVE_SALARY = 'REMOVE_SALARY ';
export const REPLACE_SALARY = 'REPLACE_SALARY';


// Roles types
export const FETCH_ROLES = 'FETCH_ROLES';
export const SET_FETCH = 'SET_FETCH';
export const STOP_FETCH = 'STOP_FETCH';
export const FETCH_ROLE = 'FETCH_ROLE';
export const ROLE_LOADING = 'ROLE_LOADING';
export const FETCHING_ROLE = 'FETCHING_ROLE';
export const STOPPED_ROLE  = 'STOPPED_ROLE';

// Gender types
export const FETCH_GENDERS = 'FETCH_GENDERS';


// NATIONLITIES types
export const FETCH_NATIONLITIES = 'FETCH_NATIONLITIES';



// COUNTRIES types
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';


// Marital types
export const FETCH_MARITALS = 'FETCH_MARITALS';

// app types
export const UPDATE_ERROR = 'UPDATE_ERRROR';
export const CLOSE_ERROR = 'CLOSE_ERROR';