version: '3'

networks:
  hyper:

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - ./api/api.conf:/etc/nginx/conf.d/default.conf
      - ../api/.:/var/www/app
    networks:
      - hyper
    depends_on:
      - "php"
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ../api/.:/var/www/app
    links:
      - db:db
    networks:
      - hyper
  db:
    image: mysql:5.7.25
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - hyper
volumes:
  dbdata:
    driver: local
